apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.20.1.149
    path: "/kubedata"
    readOnly: false
